name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      # 모든 run 명령어 앞에 'cd [프로젝트 폴더] &&'를 추가합니다.
      - name: Flutter Dependencies
        run: cd flutter_application_caculator && flutter pub get

      - name: Run Flutter Tests
        run: cd flutter_application_caculator && flutter test

      - name: Build Android App (optional)
        run: cd flutter_application_caculator && flutter build apk